name: Run Tests and Upload Artifact

on: 
  schedule:
    - cron: '35 10 * * *'  # Ejecuta a las 10:35 UTC o 12:35 UTC+2 para España
    - cron: '35 11 * * *'  # Ejecuta a las 10:35 UTC o 12:35 UTC+2 para España
  push: {}
  pull_request: {}
  workflow_dispatch: {}
  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate report
        run: node test/calculator.test.js

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results/test-results.txt
